### ISSUE TITLE
update idbiaas to work with libcloud 2.x

### ISSUE THREAD

**Issue by fkr** [idb-project/idbiaas#3]

**Comment by rbns** [comment]
installation using setup.py (e.g. using `pip install .` to install from local dir or `pip install idbiaas` to install from pypi) will always use the newest version of packages found on pypi, as (for now) no version requirements are pinned in setup.py.

upgrading dependencies in installations should work using `pip list --outdated` in the activated venv and upgrading the packages shown using `pip install $package --upgrade` .

more information about setup.py vs. requirements.txt: https://stackoverflow.com/a/33685899
